; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F405RG]
platform = ststm32
board = genericSTM32F405RG
framework = stm32cube
monitor_speed = 115200
upload_protocol = cmsis-dap
debug_tool = cmsis-dap


; 強制將速度降到極低 (50kHz) 來測試連線
upload_speed = 50 
; 避免因重置引腳 (NRST) 未連接或拉高而導致無法啟動

build_flags = 
  -DHSE_VALUE=16000000
  -Wl,-u,_printf_float
  -DUSE_HAL_DRIVER        ; 啟用 HAL 庫
  -DUSE_FULL_LL_DRIVER    ; 可選：啟用 LL 庫（與 HAL 共存）
[platformio]
src_dir = Core/Src
include_dir = Core/Inc 